export const pokemon = [
    {
        id: 1,
        name: 'zorua',
        species_id: 570,
        type: 'dark',
        category: 'tricky fox',
        ability: 'illusion',
        height: 0.7,
        weight: 12.5,
        hp: 40,
        attack: 25,
        defense: 50,
        special_attack: 80,
        special_defense: 40,
        speed: 65,
        evolves_from_species_id:'NA',
        img: `zorua.png`,        
        pokedex:'https://www.pokemon.com/us/pokedex/zorua'
    },
    {
        id: 2,
        name: 'charmander',
        species_id: 4,
        type: 'fire',
        category: 'lizard',
        ability: 'blaze',
        height: 0.6,
        weight: 8.5,
        hp: 39,
        attack: 52,
        defense: 43,
        special_attack: 60,
        special_defense: 50,
        speed: 65,
        evolves_from_species_id:'NA',
        img: `charmander.png`,        
        pokedex:'https://www.pokemon.com/us/pokedex/charmander'
    },
    {
        id: 3,
        name: 'mimikyu',
        species_id: 778,
        type: 'ghost',
        category: 'disguise',
        ability: 'disguise',
        height: 0.2,
        weight: 0.7,
        hp: 50,
        attack: 90,
        defense: 80,
        special_attack: 50,
        special_defense: 105,
        speed: 96,
        evolves_from_species_id:'NA',
        img: `mimikyu-disguised.png`,        
        pokedex:'https://www.pokemon.com/us/pokedex/mimikyu'
    },
    {
        id: 4,
        name: 'pancham',
        species_id: 674,
        type: 'fighting',
        category: 'playful',
        ability: 'iron fist',
        height: 0.6,
        weight: 8,
        hp: 67,
        attack: 82,
        defense: 62,
        special_attack: 46,
        special_defense: 48,
        speed: 43,
        evolves_from_species_id:'NA',
        img: `pancham.png`,        
        pokedex:'https://www.pokemon.com/us/pokedex/pancham/'
    },    
    {
        id: 5,
        name: 'darkrai',
        species_id: 491,
        type: 'dark',
        category: 'pitch-black',
        ability: 'bad dreams',
        height: 1.5,
        weight: 50.5,
        hp: 70,
        attack: 90,
        defense: 90,
        special_attack: 135,
        special_defense: 90,
        speed: 125,
        evolves_from_species_id:'NA',
        img: `darkrai.png`,        
        pokedex:'https://www.pokemon.com/us/pokedex/darkrai'
    },    
    {
        id: 6,
        name: 'pichu',
        species_id: 172,
        type: 'electric',
        category: 'tiny mouse',
        ability: 'static',
        height: 0.3,
        weight: 2,
        hp: 20,
        attack: 40,
        defense: 15,
        special_attack: 35,
        special_defense: 35,
        speed: 60,
        evolves_from_species_id:'NA',
        img: `pichu.png`,        
        pokedex:'https://www.pokemon.com/us/pokedex/pichu'
    },    
    {
        id: 7,
        name: 'jynx',
        species_id: 124,
        type: 'ice',
        category: 'human shape',
        ability: 'oblivious',
        height: 1.4,
        weight: 40.6,
        hp: 65,
        attack: 50,
        defense: 35,
        special_attack: 115,
        special_defense: 95,
        speed: 95,
        evolves_from_species_id: 238,
        img: `jynx.png`,
        pokedex:'https://www.pokemon.com/us/pokedex/jynx'
    },    
    {
        id: 8,
        name: 'red flabebe',
        species_id: 669,
        type: 'fairy',
        category: 'single bloom',
        ability: 'flower veil',
        height: 0.1,
        weight: 0.1,
        hp: 44,
        attack: 38,
        defense: 39,
        special_attack: 61,
        special_defense: 79,
        speed: 42,
        evolves_from_species_id:'NA',
        img: `flabebe.png`,        
        pokedex:'https://www.pokemon.com/us/pokedex/flabebe'
    },    
    {
        id: 9,
        name: 'deoxys',
        species_id: 386,
        type: 'psychic',
        category: 'DNA',
        ability: 'pressure',
        height: 1.7,
        weight: 60.8,
        hp: 50,
        attack: 150,
        defense: 50,
        special_attack: 150,
        special_defense: 50,
        speed: 150,
        evolves_from_species_id:'NA',
        img: `deoxys-normal.png`,        
        pokedex:'https://www.pokemon.com/us/pokedex/deoxys'
    },    
    {
        id: 10,
        name: 'zebstrika',
        species_id: 523,
        type: 'electric',
        category: 'thunderbolt',
        ability: 'lightning rod',
        height: 1.6,
        weight: 79.5,
        hp: 75,
        attack: 100,
        defense: 63,
        special_attack: 80,
        special_defense: 63,
        speed: 116,
        evolves_from_species_id: 552,
        img: `zebstrika.png`,
        pokedex:'https://www.pokemon.com/us/pokedex/zebstrika'
    }
];